#!/usr/bin/env bash
set -euo pipefail

echo "[SUP] :: Installing Nix..."

curl --proto '=https' \
    --tlsv1.2 -sSf -L \
    https://install.determinate.systems/nix |
    sh -s -- install

. /nix/var/nix/profiles/default/etc/profile.d/nix-daemon.sh

echo "[SUP] :: Done Installing Nix..."
